name: Build and Publish Python Package to TestPyPI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and store distribution
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install pypa/build
      run: |
        python -m pip install --upgrade pip
        pip install build
    - name: Create alpha tag 0.0.0a0.devN
      run: git tag 0.0.0a0.dev$(git rev-parse --short HEAD | cut -c 1-7 | xxd -p | tr -d '\n' | printf "%d" "0x$(cut -c 1-7)")
    - name: Build package
      run: python -m build
    - name: Store the distribution packages
      uses: actions/upload-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
  publish:
    name: Publish python distribution to TestPyPI
    needs:
      - build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/project/stmeasures
    permissions:
      id-token: write
    steps:
    - name: Download distribution
      uses: actions/download-artifact@v3
      with:
        name: python-package-distributions
        path: dist/
    - name: Publish distribution to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
