name: Lint, build and test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint-build-test:
    name: Lint, build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Python Linter (ruff)
      run: |
        ruff check
    - name: C Linter (clang)
      uses: cpp-linter/cpp-linter-action@v2.13.1
      id: linter
      env:
        GITHUB_TOKEN: ${{ secrets.CLINT_TOKEN }}
      with:
        style: 'file'
        tidy-checks: ''
        thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
    - name: Build C shared library
      run: |
        make
    - name: Running tests
      run: |
        pytest
