name: Lint, build and test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint Python and C source files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.x"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install ruff pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with Ruff
      run: |
        ruff check
    - name: C/C++ Linter
      uses: cpp-linter/cpp-linter-action@v2.13.1

